name: Next.js Security Scan

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g snyk
          npm install -g snyk-to-html

      # Désactiver temporairement les vérifications TypeScript strictes pour le build
      - name: Create temporary ESLint config
        run: |
          echo '{
            "extends": "next/core-web-vitals",
            "rules": {
              "@typescript-eslint/no-explicit-any": "warn"
            }
          }' > .eslintrc.json

      - name: Build Next.js application
        continue-on-error: true
        run: npm run build

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Security Tests
        run: |
          snyk test --json | tee snyk-results.json || true
          snyk code test --json | tee snyk-code-results.json || true
          
      - name: Generate HTML Reports
        run: |
          if [ -f snyk-results.json ]; then
            snyk-to-html -i snyk-results.json -o snyk-dependency-results.html || true
          fi
          if [ -f snyk-code-results.json ]; then
            snyk-to-html -i snyk-code-results.json -o snyk-code-results.html || true
          fi

      - name: Upload Security Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: |
            *.json
            *.html
