name: Next.js Security Scan

on:
  push:
    branches: [ "main", "develop" ]
  
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Version recommandée pour Next.js
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm run build

      - name: Run Snyk to check for vulnerabilities (Dependencies)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=high

      - name: Run Snyk to check for vulnerabilities (Code)
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --severity-threshold=high

      - name: Scan Next.js Configuration
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --all-projects --configuration-matching="next.config.js"

      - name: Generate HTML report
        if: always()
        run: snyk test --json > snyk-results.json && snyk-to-html -i snyk-results.json -o snyk-results.html

      - name: Upload Snyk reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: snyk-reports
          path: |
            snyk-results.json
            snyk-results.html
