name: CI/CD AgricoWeb

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependance:
    runs-on: ubuntu-latest
    steps:
      # Vérification du code source
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Afficher la structure des répertoires (optionnel)
      - name: Debug - Show directory structure
        run: |
          echo "Current directory: $PWD"
          echo "Directory content:"
          ls -la
          echo "Full directory tree:"
          tree -a || (apt-get update && apt-get install -y tree && tree -a)
          
      # Configuration de Node.js pour Next.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Installer les dépendances
      - name: Install dependencies
        run: npm install

  snyk-security:
    runs-on: ubuntu-latest
    needs: dependance
    steps:
      - uses: actions/checkout@master
      
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
        
      - name: Run Snyk to check vulnerability 
        uses: snyk/actions/node@master
        continue-on-error: true 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test --all-projects --dep-graph --json-file-output=snyk-result.json
          
      - name: Generate Snyk HTML report
        if: always()
        run: | 
          npm install -g snyk-to-html
          snyk-to-html -i snyk-result.json -o snyk-report.html
      
      - name: Upload Snyk report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.html
      
      # Configuration de Node.js pour Snyk
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
        
      # Exécuter Snyk pour vérifier les vulnérabilités 
      - name: Run Snyk to check vulnerability 
        uses: actions/checkout@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: test --severity-threshold=medium --json-file-output=snyk-result.json

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: snyk-security
    steps:
      # Vérification du code source
      - uses: actions/checkout@v3

      # Configuration de Node.js pour le build Next.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
        
      # Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Construire l'application Next.js
      - name: Build Next.js Application
        run: npm run build

      # Déployer l'application (exemple avec Vercel)
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: npx vercel --prod
